Repository quicwg/multipath, pull requests merged in 2024-11, with the labels that each got.

#452 Typo "frames"
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#467 Add guidance on handling of PTO
  draft-ietf-quic-multipath.md
Labels: clarification

#463 Add clarification for PATHS_BLOCKED frame.
  draft-ietf-quic-multipath.md
Labels: ready-to-merge

#456 PATH_ACK can still be sent after PATH_ABANDON
  draft-ietf-quic-multipath.md
Labels: ready-to-merge

#464 Wrong subsection alignment
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#465 minor wording clarification for idle time
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge
