Repository quicwg/multipath, pull requests merged in 2024-09, with the labels that each got.

#403 Describe the effect of disable_active_migration more accurately
  draft-ietf-quic-multipath.md
Labels: needs-discussion

#416 Editorial: add reference for MP_NEW_CONN_ID frame
  draft-ietf-quic-multipath.md
Labels: editorial

#419 SHOULD use MP frame for path ID 0
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#420 PATH_ABANDON on broken path
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#428 Remove MP_PROTOCOL_VIOLATION
  draft-ietf-quic-multipath.md
Labels: ready-to-merge

#389 remove probing concept and text on migration
  draft-ietf-quic-multipath.md
Labels: needs PR, ready-to-merge

#427 Rename PATH_STANDBY to PATH_BACKUP
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#426 Rename MP_* frames to PATH_*
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#418 Editorial: fix requirement of opening a new path
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#433 Fix: TRANSPORT_PARAMETER should be TRANSPORT_PARAMETER_ERROR
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#402 Add MAX_PATH_ID_BLOCKED frame and related texts
  draft-ietf-quic-multipath.md
Labels: needs-review

#431 Delaying of PATH_RESPONSE
  draft-ietf-quic-multipath.md
Labels: design

#429 Do not delete both duplicate paths
  draft-ietf-quic-multipath.md
Labels: needs-review

#388 Clarify denying a path and move text
  draft-ietf-quic-multipath.md
Labels: needs-review

#435 remove the term "active path" as it was not well defined
  draft-ietf-quic-multipath.md
Labels: editorial, needs-review

#437 Propose new text for new token policy
  draft-ietf-quic-multipath.md
Labels: needs-review

#396 Proposal to make path status sequence number per path.
  .github/workflows/ghpages.yml
  .github/workflows/publish.yml
  draft-ietf-quic-multipath.md
Labels: needs-discussion
