Repository quicwg/multipath, pull requests merged in 2024-10, with the labels that each got.

#438 Update Acknowledgement section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#439 Connection ID sequence number space starts at 0 for all paths
  draft-ietf-quic-multipath.md
Labels: ready-to-merge, clarification

#441 add ref to DPLPMTUD
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#447 minor clarification on remembering the transport parameter
  draft-ietf-quic-multipath.md
Labels: editorial

#443 Add implementation comments for key rotation.
  draft-ietf-quic-multipath.md
Labels: ready-to-merge

#444 Add more guidance on when to use PATH_ACK frames
  draft-ietf-quic-multipath.md
Labels: ready-to-merge

#442 packets without challenge are valid
  draft-ietf-quic-multipath.md
Labels: ready-to-merge

#440 new text on idle timeouts
  draft-ietf-quic-multipath.md
Labels: ready-to-merge

#445 Dev/add error code
  draft-ietf-quic-multipath.md
Labels: needs-review
