Repository quicwg/multipath, pull requests merged in 2025-04, with the labels that each got.

#522 Move error codes into PATH-ABANDON section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#515 editorial pass on security considerations section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#520 Add a ref to BCP 133 for future CC designers
  draft-ietf-quic-multipath.md
Labels: ready-to-merge, clarification

#523 Edits on migration guidance section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#524 Remove redundancy on use of PATH_NEW/RETIRE_CID frames
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#526 nits in path status section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#530 small editorial changes on "same 4-tuple" section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#532 Update IANA section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#534 Headings in implementation guidance section
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#531 editorial pass packet scheduling section
  draft-ietf-quic-multipath.md
Labels: editorial

#536 note on sending data frames on different paths
  draft-ietf-quic-multipath.md
Labels: ready-to-merge, clarification

#537 use only path ID
  draft-ietf-quic-multipath.md
Labels: editorial, ready-to-merge

#533 Merge idle timeout and keep alive section
  draft-ietf-quic-multipath.md
Labels: editorial

#540 Some remaining small editorial improvements from Gorry
  draft-ietf-quic-multipath.md
Labels: editorial
